### ISSUE TITLE
project(":server").afterEvaluate looks strange in client/build.gradle

### ISSUE THREAD

**Issue by vlsi** [Kotlin/kotlin-full-stack-application-demo#3]
The following looks suspicious

https://github.com/Kotlin/kotlin-full-stack-application-demo/blob/ade07b879ec449d7ae9ad9bd3bb17baeee09543a/client/build.gradle#L53-L57

What is the purpose of the code?

Should it be written as

```gradle
run {
    dependsOn ":server:prepareDevServer"
}
```

?

**Comment by ilgonmic** [comment]
Thanks, I fixed it 1.4 branch (https://github.com/Kotlin/kotlin-full-stack-application-demo/blob/1.4/client/build.gradle.kts#L58)
