### ISSUE TITLE
Bad cross-project publication used

### ISSUE THREAD

**Issue by Vampire** [Kotlin/kotlin-full-stack-application-demo#9]
`server/build.gradle.kts` uses this:
```kts
tasks.withType<Copy>().named("processResources") {
    from(project(":client").tasks.named("browserDistribution"))
}
```
This is not only bad practice, it only works by accident, is unsafe and can lead to non-reproducible and hard to parallelize builds.

You can find more information and how to do it properly on https://docs.gradle.org/current/userguide/cross_project_publications.html

**Comment by ilgonmic** [comment]
Thank you!
Fixed in f1ae60764207145d8000c05b6978ee0e50d6fd1b
